---
title: "D607 Final Project"
author: "Marco Castro"
date: "2024-11-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(httr)
library(purrr)
library(stringr)
library(rvest)
library(textutils)
```

## Overview

This script scrapes the [Zillow] ("https://www.zillow.com/").

```{r init-scraper}

# custom function for delayed scraping
throttled_GET <- slowly(
  ~read_html(.),
  rate = rate_delay(2)
)

# global vars
domain <- "https://www.zillow.com"
zip <- "14201"
beds <- 0

# update user agents
user_agent <- "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763"
set_config(add_headers(`User-Agent` = user_agent))

# Read first search 
path <-paste(domain, "/", zip, "/rentals/", sep="") 
realestate_data <- throttled_GET(path)

```


```{r read-html-on-page}

# grab listings div from html on this page
result_container <- realestate_data %>% 
  html_element(xpath = '//div[@class="result-list-container"]' )

# C2. grab the pagination list items
pagination <- result_container %>% 
  html_element(xpath = '//nav[@class="StyledPagination-c11n-8-107-0__sc-4uav85-0 dOdLEd"]') %>% 
  html_elements(xpath = '//li[@class="PaginationNumberItem-c11n-8-107-0__sc-i6f8qs-0 lTbnm"]') %>% 
  html_text() %>%
  strsplit(" ")

# get the total number of search result pages
current_page <- 1
last_page = as.numeric(pagination[length(pagination)]) + 1

# C3: get the listings on this page
listings <- result_container %>% 
  html_element(xpath = 'ul' ) %>%   
  html_elements(xpath = 'li' ) %>%
  html_elements(xpath = '//span[@data-test="property-card-price"]' )  %>%
  html_text()

```

```{r clean-up-listing-price}


# init market rate tibble
market_rates <- tibble(
  zip_code = character(),
  bedrooms = integer(),
  monthly_rent = integer()
)

# custom function to remove misc chars
cleanup_price <- function(s) {
  t <- str_replace_all(s, "([$,])", "") #remove dollar signs and commas
  x <- gsub("^([0-9]+).*", "\\1", t) #only return first group of integers
  print(x)
  return(as.integer(x))
} 

# loop through all listing prices 
# and append to market rate tibble
for (s in listings)
  market_rates <- market_rates |>
    add_row(zip_code = zip, bedrooms = beds, monthly_rent = cleanup_price(s))


head(market_rates, n=10)
```



This section crawls through each search result page and grabs the unique job listing id. This will be used later to crawl the individual job listing page.




```{r crawl-search-result-pages}


# init the page counter
current_page <- 1

# init the page_ids data frame
page_ids <- data.frame()

# loop though all pages
while (current_page < last_page) {

    # This tells us to go to the next page
    current_page <- current_page + 1
}


```
